# Generated by Django 3.1.7 on 2021-04-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0002_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_title', models.CharField(max_length=200)),
                ('Goal_date', models.DateTimeField(verbose_name='Goal created')),
                ('entry', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_title', models.CharField(max_length=200)),
                ('Goal_date', models.DateTimeField(verbose_name='Goal created')),
                ('entry', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
