# Generated by Django 3.1.7 on 2021-04-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0003_goals_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
