# Generated by Django 3.1.7 on 2021-04-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0005_auto_20210424_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_title', models.CharField(max_length=200)),
                ('achievement_text', models.TextField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisegamification.profile')),
            ],
        ),
    ]
