# Generated by Django 3.1.7 on 2021-04-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0008_auto_20210406_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_exercise',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
