# Generated by Django 3.1.7 on 2021-04-06 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0009_auto_20210406_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisegamification.profile'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_text',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
