# Generated by Django 3.1.7 on 2021-04-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0010_auto_20210406_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
