# Generated by Django 3.1.6 on 2021-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0011_auto_20210405_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_text',
            field=models.TextField(null=True, verbose_name='goal description'),
        ),
    ]
