# Generated by Django 3.1.6 on 2021-04-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0011_auto_20210406_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_exercise',
        ),
    ]
