# Generated by Django 3.1.7 on 2021-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0012_auto_20210424_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
