# Generated by Django 3.1.6 on 2021-04-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0012_remove_profile_fav_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_exercise',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
