# Generated by Django 3.1.7 on 2021-04-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0013_auto_20210412_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='created',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='updated',
        ),
    ]
