# Generated by Django 3.1.7 on 2021-04-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0013_achievement_achievement_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisegamification.profile'),
        ),
    ]
