# Generated by Django 3.1.6 on 2021-04-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0014_auto_20210408_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='reach_date',
            field=models.DateTimeField(verbose_name='reach date'),
        ),
    ]
