# Generated by Django 3.1.7 on 2021-04-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0014_auto_20210424_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievement',
            new_name='PointAchievement',
        ),
    ]
