# Generated by Django 3.1.7 on 2021-05-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0015_auto_20210424_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_achievement_title', models.CharField(max_length=200)),
                ('goal_achievement_text', models.TextField(blank=True, max_length=500, null=True)),
                ('goal_achievement_threshold', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercisegamification.profile')),
            ],
        ),
    ]
