# Generated by Django 3.1.6 on 2021-04-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0015_auto_20210408_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points_total',
            field=models.IntegerField(default=0),
        ),
    ]
