# Generated by Django 3.1.7 on 2021-05-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0016_goalachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='reach_date',
            field=models.DateField(verbose_name='reach date'),
        ),
    ]
