# Generated by Django 3.1.7 on 2021-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0018_auto_20210504_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointachievement',
            name='icon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
