# Generated by Django 3.1.7 on 2021-05-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercisegamification', '0020_auto_20210505_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointachievement',
            name='icon',
        ),
    ]
